apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'go-app'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'default'
  source:
    path: 'chart'
    repoURL: 'https://github.com/tanya-domi/gitops-workflow-deploy-goapp-using-argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
